[package]
name = "rust-to-onem2m"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = "1"
uuid = "1.7"
reqwest = { version = "0.11", features = ["json"] }
